# Heroku process configuration

# nginx + gunicorn (recommended)
web: bin/start-nginx gunicorn --config gunicorn_config_heroku.py --bind unix:///tmp/wsgi-app.socket wsgi:application

# Async worker
worker: cd django-root && celery -A django_site worker --without-gossip --without-mingle --without-heartbeat --max-tasks-per-child=1 --concurrency=2

# waitress + whitenoise (simpler but more server load)
#web: cd django-root && waitress-serve --port=$PORT wsgi:application

#
release: cd django-root && ./manage.py migrate --noinput
