# Generated by Django 4.2.3 on 2023-09-24 23:34

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        (
            "scbp_core",
            "0006_remove_booking_scbp_core_booking_booking_payment_method_valid_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="driver_collect_method",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "-"), (2, "Credit Card"), (1, "Cab Charge"), (3, "Cash")],
                default=0,
            ),
        ),
    ]
