# Generated by Django 4.2.3 on 2023-09-28 02:43

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("scbp_core", "0008_account_driver_collect_data_migrations"),
    ]

    operations = [
        # For reasons that make no sense, Django is telling us that it should delete this constraint
        # ... then immediately after, it tells us that this constraint is missing, and should be created
        # ... but the new constraint is identical to the old constraint
        # ... :shrug:
        migrations.RemoveConstraint(
            model_name="booking",
            name="scbp_core_booking_booking_payment_method_valid",
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                check=models.Q(("booking_payment_method__in", [1, 2, 3])),
                name="scbp_core_booking_booking_payment_method_valid",
            ),
        ),
    ]
