# Generated by Django 4.2.3 on 2023-09-17 23:26

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("scbp_core", "0002_sql_statements"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="booking_payment_method2",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Invoice"), (2, "Credit Card"), (3, "Driver Collect")],
                default=2,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="driver_collect_method",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "-"), (2, "Credit Card"), (1, "Cab Charge"), (3, "Cash")],
                default=0,
            ),
        ),
    ]
