# Generated by Django 4.2.3 on 2023-09-18 00:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("scbp_core", "0004_payment_method_data_migrations"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="booking_payment_method",
        ),
        migrations.RenameField(
            model_name="booking",
            old_name="booking_payment_method2",
            new_name="booking_payment_method",
        ),
    ]
