# Generated by Django 4.2.3 on 2023-09-18 00:59

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("scbp_core", "0005_remove_booking_payment_method_rename"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                check=models.Q(("booking_payment_method__in", [1, 2, 3])),
                name="scbp_core_booking_booking_payment_method_valid",
            ),
        ),
    ]
