# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-26 17:03
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TestModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.CharField(max_length=255)),
            ],
            options={"db_table": "django_cypress_test_model"},
        )
    ]
