# Safety Security and License Configuration file
# We recommend checking this file into your source control in the root of your Python project
# If this file is named .safety-policy.yml and is in the same directory where you run `safety check` it will be used by default.
# Otherwise, you can use the flag `safety check --policy-file <path-to-this-file>` to specify a custom location and name for the file.
# To validate and review your policy file, run the validate command: `safety validate policy_file --path <path-to-this-file>`
security: # configuration for the `safety check` command
    ignore-cvss-severity-below: 0 # A severity number between 0 and 10. Some helpful reference points: 9=ignore all vulnerabilities except CRITICAL severity. 7=ignore all vulnerabilities except CRITICAL & HIGH severity. 4=ignore all vulnerabilities except CRITICAL, HIGH & MEDIUM severity.
    ignore-cvss-unknown-severity: False # True or False. We recommend you set this to False.
    ignore-vulnerabilities: # Here you can list multiple specific vulnerabilities you want to ignore (optionally for a time period)
        # We recommend making use of the optional `reason` and `expires` keys for each vulnerability that you ignore.
        60956: # vulnerability ID
            reason: django - Potential denial of service vulnerability in django.utils.encoding.uri_to_iri() # optional, for internal note purposes to communicate with your team. This reason will be reported in the Safety reports
            expires: '2024-02-19' # datetime string - date this ignore will expire, best practice to use this variable
        61191:
            reason: grpcio - Lack of error handling in the TCP server in Google's gRPC
            expires: '2024-02-19'
        61586:
            reason: django - Denial-of-service possibility in django.utils.text.Truncator
            expires: '2024-02-19'
        61601:
            reason: urllib3 - Possibility of user to specify 'Cookie' header and leak information via HTTP redirects to a different origin if redirects not disabled explicitly
            expires: '2024-02-19'
        61657:
            reason: aiohttp - LLHTTP security issue
            expires: '2024-02-19'
        61893:
            reason: urllib3 - Request body not stripped after redirect from 303 status changes request method to GET
            expires: '2024-02-19'
        62126:
            reason: django - Potential denial of service vulnerability in UsernameField on Windows
            expires: '2024-02-19'
        62326:
            reason: aiohttp - HTTP parser in AIOHTTP has numerous problems with header parsing
            expires: '2024-02-19'
        62582:
            reason: aiohttp - Improper validation might allow attacker to modify/create HTTP request
            expires: '2024-02-19'
        62583:
            reason: aiohttp - Improper validation might allow attacker to modify/create HTTP request
            expires: '2024-02-19'
        64436:
          reason: pillow - Arbitrary code execution vulnerability
          expires: '2024-02-19'
        64437:
          reason: pillow - Potential vulnerability to DoS attacks through PIL
          expires: '2024-02-19'
        64438:
          reason: pillow - Potential vulnerability to DoS attacks through PIL
          expires: '2024-02-19'
    continue-on-vulnerability-error: False # Suppress non-zero exit codes when vulnerabilities are found. Enable this in pipelines and CI/CD processes if you want to pass builds that have vulnerabilities. We recommend you set this to False.
